kubernetes-sigs/cluster-api-ipam-provider-in-cluster

- Makefile
We had issues running `make install`. Kustomize threw this error:
```
$ make install
...
/home/user/workspace/cluster-api-ipam-provider-in-cluster/hack/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases                                                    env GOBIN=/home/kokoni/workspace/cluster-api-ipam-provider-in-cluster/hack/bin go install sigs.k8s.io/kustomize/kustomize/v3@v3.8.7
go: sigs.k8s.io/kustomize/kustomize/v3@v3.8.7 (in sigs.k8s.io/kustomize/kustomize/v3@v3.8.7):                                                                                                                                                    The go.mod file for the module providing named packages contains one or …
```
> Bump kustomize to 4.5.7

- go.mod
- main.go
- this keeps it consistent with other capi loggers such as CAPV
- this logger prints timestamps in a human readable format by default
Fixes #69
> Change logger from zap to klog

- go.mod
- go.sum
- internal/index/index.go
- internal/poolutil/pool.go
- internal/poolutil/pool_test.go
- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
Replaces `inet.af/netaddr` with `net/netip` and `go4.org/netipx` since it is deprecated and does not build with go 1.20.
`netipx` contains everything fro `netaddr` that didn't make it into `net/netip` and is compatible with its types.
> replace inet.af/netaddr with net/netip and netipx

- config/manager/manager.yaml
This does not really change the configuration, it just makes it explicit and enforce the defaults, except for the seccompPolicy which changes from Unconfined to RuntimeDefault. Syscalls filtered by RuntimeDefault policy are 95% namespaced and require capabilities (which we drop) in the first place, so no practical change there either.
This allows to be compatible to the restricted pod security admission profile.
This is a recommendation in the [CAPI v1.3->1.4 upgrade guide](https://main.cluster-api.sigs.k8s.io/developer/providers/migrations/v1.3-to-v1.4.html#suggested-changes-for-providers).
**Special notes for your reviewer**:
Prior art:
* https://github.com/kubernetes-sigs/cluster-api/pull/7831
* …
> add explicit securityContexts to the controller

- internal/controllers/ipaddressclaim.go
- internal/controllers/ipaddressclaim_test.go
- internal/index/index.go
- internal/poolutil/pool.go
InClusterIPPools support a .spec.paused property which will pause the reconciliation of claims referencing that pool
> support pausing pools

- CONTRIBUTING.md
- OWNERS
- OWNERS_ALIASES
- README.md
- SECURITY_CONTACTS
This PR adds the necessary template files from https://github.com/kubernetes/kubernetes-template-project for the move to kubernetes-sigs.
There are probably a few areas that can be fleshed out more that haven't been yet. Here are some things in no particular order:
* For the contributing.md it was left fairly vanilla from the template file, except I added a contributing a patch section taken from the cluster-api-provider-vsphere contributing.md.
* For the Owners Alias, it currently only has @schrej, but we could add some/all of the VMware based contributors we have on our team (@tylerschultz @adobley @flawedmatrix and @christianang). Wasn't sure if it was better to do it before or after the move so I left it as is. Same with the Security Contacts file.
* For the readme II added the …
> Add necessary kubernetes template files for kubernetes-sigs move

- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
- require IPv4 Gateway if addresses are IPv4
- continue to not require IPv6 Gateway if addresses are IPv6
- validate addresses are of the same family i.e cannot mix IPv4 and IPv6 addresses in a single pool
- validate addresses and gateway are of the same family (if gateway is provided)
Relates to #70
We did some experimenting around cases with and without Gateway. We think this PR represents common understandings and preferences. This PR puts forth that Gateway should be required with pools/addresses that are IPv4, and Gateway should be optional when addresses are IPv6. We're open to feedback if these choices seem incorrect or too heavy handed.
We see that (at least in our envs) that we are able to launch IPv6 machines without configuring a Gateway. The default route is provided by Router …
> Add validation for IP family and gateways

- config/webhook/manifests.yaml
- go.mod
- go.sum
- internal/controllers/inclusterippool.go
- internal/controllers/inclusterippool_test.go
- internal/controllers/ipaddressclaim_test.go
- internal/index/index.go
- internal/poolutil/pool.go
- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
- internal/webhooks/util_test.go
Adds a finalizer to prevent pool deletion when IPs are still allocated
Adds a delete webhook check that will ensure pools with allocated IPs cannot be removed
This change relies on work in #116, when that is merged we can rebase this.
Fixes #114
> protect pools with IP allocations from deletion

- api/v1alpha1/inclusterippool_types.go
- config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
- internal/controllers/inclusterippool.go
- internal/controllers/inclusterippool_test.go
- internal/poolutil/pool.go
- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
In the case that the a pool is still updated and has out of range IPs display the count in the pool status
Relies on #116, we can update this when that is merged
Fixes #117, with the exception of `In addition to the outOfRange status count on the pool we could also add an outOfRange status condition on the IPAddress.`
This last bit would require changes to the IPAddress resource in core CAPI. The Status field is missing on the IPAddress objects. We think this is okay for now and we can open a new issue for that if we still think it is valuable.
> Webhook Validate updated pool does not remove in use IPs

- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
This PR adds a `ipam.cluster.x-k8s.io/skip-validate-delete-webhook` annotation that can be added to pools to skip delete validation. This is necessary for clusterctl move to work because it attempts to delete everything off the source cluster and it cannot control the order of deletion so it may delete pools before ipaddressclaims.
Related to #140
> :bug: Add skip validate delete webhook annotation

- .golangci.yml
- PROJECT
- README.md
- go.mod
- hack/version.sh
- internal/controllers/inclusterippool.go
- internal/controllers/inclusterippool_test.go
- internal/controllers/ipaddressclaim.go
- internal/controllers/ipaddressclaim_test.go
- internal/controllers/suite_test.go
- internal/poolutil/pool.go
- internal/poolutil/pool_test.go
- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
- main.go
- pkg/types/types.go
Today the code was migrated keeping the old reference to the original repo. This becomes a problem while trying to use/import some helper functions, etc :)
> :bug: Migrate modules to right path

- internal/controllers/ipaddressclaim.go
- internal/controllers/ipaddressclaim_test.go
Clusters can be paused by annotation or by spec.paused. If either are true, skip claim reconcilliation that are associated to those claims.
Fixes #136
> 🐛 Update cluster paused detection

- api/v1alpha1/inclusterippool_types.go
- api/v1alpha2/inclusterippool_types.go
- config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
This PR adds the category `cluster-api` to the custom resource definitions.
By doing that it follows the prior art in core CAPI and providers to populate the category field.
By this change a `kubectl get cluster-api` query will also output this CRs.
Fixes #
> 🌱 Add `categories=cluster-api` to the crd

- OWNERS_ALIASES
> 🌱 add rikatz to reviewers

- Dockerfile
- Makefile
- cloudbuild.yaml
Improves build automation for staging images and aligns it with cluster-api's setup. This includes support for multi-arch images.
> 🌱 improve image building

- Dockerfile
Bumps the Go version used to build container images to 1.21
Fixes #
/lgtm
/approve
> 🐛 bump go version for container images to 1.21

- config/default/kustomization.yaml
- config/default/manager_webhook_patch.yaml
- tilt-provider.yaml
Replaces the `caip-in-cluster` prefix with `capi-ipam-in-cluster` to be in line with the future image name. It was pointed out that caip just looks like a misspelling of capi.
I think this will lead to issues when upgrading existing deployments with clusterctl and would require to manually uninstall the provider first.
> ⚠️ align prefix of deployments with image name

- README.md
The README docs mention the older `~/.cluster-api` configuration directory for accessing the clusterctl.yaml file. This should now point to `$XDG_CONFIG_HOME/cluster-api` instead.
**Which issue(s) this PR fixes**:
N/A
> 🌱 Update to current preferred config directory

- config/crd/kustomization.yaml
- config/crd/patches/clusterctl-label_in_globalinclusterippools.yaml
- config/crd/patches/clusterctl-label_in_inclusterippools.yaml
Adds `clusterctl.cluster.x-k8s.io/move-hierarchy` to the CRDs, which causes clusterctl to move pools and all their addresses when the pool has a `cluster.x-k8s.io/cluster-name` label.
#212
> 🌱 add clusterctl move-hierarchy labels to pools

- Makefile
Appends `-controller` to image name to align it with other providers. Not considered a breaking change since we've never published images on the official registries for this project.
> 🐛 align image name with other capi providers

- internal/controllers/ipaddressclaim_test.go
- pkg/ipamutil/reconciler.go
CAPI has a contract to label all created resources with a ClusterName label. CAPV will label IPAddressClaim. This PR is to ensure IPAddress also got one.
Please find more discussion in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2218
Fixes #
> Ensure IPAddress has a ClusterName label as CAPI resources

- internal/controllers/ipaddressclaim.go
- pkg/ipamutil/reconciler.go
**What this PR does / why we need it**: The interface for ClaimHandler does not request a context on ReleaseAddress method.
We need the context here, as to get/use the Kubernetes client, and any other client (eg. an IPAM HTTP Rest API) during the release we may need the current context. 
**Note**: This is marked as a Warning/Breaking change, because we are changing a public interface
> :warning: ReleaseAddress should receive a context

- Makefile
- config/default/manager_image_patch.yaml
Replaces the images in release manifests with registry.k8s.io ones as we're now able to use those.
Fixes #
> 🌱 use registry.k8s.io image in release manifests

- OWNERS_ALIASES
> 🌱 Add mcbenjemaa to OWNERS_ALIASES

- Makefile
Fixes conversion-gen to use a version tag instead of using latest
Also removes `--output-base` since it is no longer a valid tag
Fixes #
> 🌱 Update conversion-gen to a fixed tag

- .github/workflows/pullrequests.yaml
- .golangci.yml
- api/v1alpha1/inclusterippool_types.go
- api/v1alpha2/inclusterippool_types.go
- config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
- internal/controllers/inclusterippool_test.go
- internal/poolutil/pool.go
Upgrades golangci-lint to 1.60.2
Configuration is mostly copied from CAPI, removing the unnecessary parts
A few changes to make the linter happy
Fixes #
> 🌱 upgrade golangci-lint and it's config and make it happy

- tilt-provider.yaml
- This is a small fix to be able to use tilt in other project referring to this project.
While testing cluster-api-proxmox (which has tilt reference to this project), I found that tilt was not able to build this provider.  Digging into it I found that the image reference was changed from "telekom" to "k8s-staging-capi-ipam-ic". However, this reference was not updated. @schrej can you perhaps acknowledge that this is the correct fix?
> 🐛 Fix image reference in tilt-provider.yaml

- .github/workflows/draft_release.yaml
This PR adds the missing permission required to create a draft release 
Fixes #
> Make github action able to create a draft release

- api/v1alpha2/inclusterippool_types.go
- config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
- config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
- internal/poolutil/pool_test.go
- internal/webhooks/inclusterippool.go
- internal/webhooks/inclusterippool_test.go
This PR allows the IPPoolSpec to have /0 prefix.
I added tests for webhook and pool spec.
Closes #287
> Allow IPPool to have Prefix /0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/release.md
This PR adds:
- Issue templates
> 🌱  Add issues templates

- README.md
> add note about ipv6 pool status to readme

- internal/controllers/ipaddressclaim_test.go
- pkg/ipamutil/reconciler.go
Currently there is a bug, that if you delete a cluster, which is referenced in an IPAddressClaim, the IPAddressClaim won't be deleted and in the log, the following message is shown instead:
`IPAddressClaim linked to a cluster that is not found, unable to determine cluster's paused state, skipping reconciliation`
This is due to the function `r.reconcileDelete()` only deleting the ReleaseAddressFinalizer in the local copy of the claim and not in the actual object. The update of the object is missing.
This PR fixes this behaviour by adding the update clause to update the object in k8s/etcd.
> :bug: fix skipping reconciliation, when a referenced cluster is already deleted

- main.go
For local development and some cases where webhooks cannot be used, adds an option via env variable to disable them.
> :seedling: add webhook flags

- .golangci.yml
- pkg/ipamutil/reconciler.go
This PR is based on the changes from @schrej and fixes a bug, where ReleaseAddress is not getting called during deletion.
Additionally it fixes an error regarding to error handling:
`err := errors.New("pool not found")`
This hides the error of FetchPool(). Instead it should be wrapped/enhanced by the new error.
And changes some behaviour regarding the finalizer patching. The defer is moved down and the finalizer patching is now done explicitly instead of implicitly by the defer.
> :bug: properly handle deletion of IPAddressClaims in ipamutil.ClaimReconciler

- .github/workflows/draft_release.yaml
- .github/workflows/pullrequests.yaml
- cloudbuild.yaml
Bump Cloud build to `v20250513-9264efb079`.
Use go-version-file: go.mod for setup-go action
Fixes #
> 🌱 Bump cloudbuild, and use go-version-file for setup-go action
